#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = %cd%

CC = gcc.exe
CXX = g++.exe
AR = ar.exe
LD = g++.exe
WINDRES = windres.exe

_INC = 
# _CFLAGS = -Wall -fexceptions
_RESINC = 
_LIBDIR = 
_LIB = 
_LDFLAGS = 

# INC_DEBUG = $(INC) -Iinclude
# CFLAGS_DEBUG = $(CFLAGS) -g
# RESINC_DEBUG = $(RESINC)
# RCFLAGS_DEBUG = $(RCFLAGS)
# LIBDIR_DEBUG = $(LIBDIR)
# LIB_DEBUG = $(LIB)
# LDFLAGS_DEBUG = $(LDFLAGS)
# OBJDIR_DEBUG = obj\\Debug
# DEP_DEBUG = 
# OUT_DEBUG = bin\\Debug\\sim_cache.exe

# INC_RELEASE = $(INC) -Iinclude
# CFLAGS_RELEASE = $(CFLAGS) -O2
# RESINC_RELEASE = $(RESINC)
# RCFLAGS_RELEASE = $(RCFLAGS)
# LIBDIR_RELEASE = $(LIBDIR)
# LIB_RELEASE = $(LIB)
# LDFLAGS_RELEASE = $(LDFLAGS) -s
# OBJDIR_RELEASE = obj\\Release
# DEP_RELEASE = 
# OUT_RELEASE = bin\\Release\\sim_cache.exe

INC = $(_INC) -Iinclude
CFLAGS = $(_CFLAGS) -O2
RESINC = $(_RESINC)
RCFLAGS = $(RCFLAGS)
LIBDIR = $(_LIBDIR)
LIB = $(_LIB)
LDFLAGS = $(_LDFLAGS) -s
OBJDIR = obj
DEP = 
OUT = sim_cache.exe


# OBJ_DEBUG = $(OBJDIR_DEBUG)\\main.o $(OBJDIR_DEBUG)\\src\\Block.o $(OBJDIR_DEBUG)\\src\\Cache.o $(OBJDIR_DEBUG)\\src\\Set.o

# OBJ_RELEASE = $(OBJDIR_RELEASE)\\main.o $(OBJDIR_RELEASE)\\src\\Block.o $(OBJDIR_RELEASE)\\src\\Cache.o $(OBJDIR_RELEASE)\\src\\Set.o

OBJ = $(OBJDIR)\\main.o $(OBJDIR)\\src\\Block.o $(OBJDIR)\\src\\Cache.o $(OBJDIR)\\src\\Set.o

# all: debug release
all: sim_cache
	@echo "my work is done here..."

# clean: clean_debug clean_release

before: 
# 	cmd /c if not exist bin\\Debug md bin\\Debug
	cmd /c if not exist $(OBJDIR) md $(OBJDIR)
	cmd /c if not exist $(OBJDIR)\\src md $(OBJDIR)\\src

after: 

sim_cache: before out after

out: before $(OBJ) $(DEP)
	$(LD) $(LIBDIR) -o $(OUT) $(OBJ)  $(LDFLAGS) $(LIB)

$(OBJDIR)\\main.o: main.cpp
	$(CXX) $(CFLAGS) $(INC) -c main.cpp -o $(OBJDIR)\\main.o

$(OBJDIR)\\src\\Block.o: src\\Block.cpp
	$(CXX) $(CFLAGS) $(INC) -c src\\Block.cpp -o $(OBJDIR)\\src\\Block.o

$(OBJDIR)\\src\\Cache.o: src\\Cache.cpp
	$(CXX) $(CFLAGS) $(INC) -c src\\Cache.cpp -o $(OBJDIR)\\src\\Cache.o

$(OBJDIR)\\src\\Set.o: src\\Set.cpp
	$(CXX) $(CFLAGS) $(INC) -c src\\Set.cpp -o $(OBJDIR)\\src\\Set.o

clean: 
	cmd /c del /f $(OBJ) $(OUT)
# 	cmd /c rd bin\\Debug
	cmd /c rd $(OBJDIR)\\src
	cmd /c rd $(OBJDIR)

.PHONY: before after clean

